name: firebase_auth_web
description: The web implementation of firebase_auth
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_auth/firebase_auth_web
version: 0.4.0-1.1.nullsafety.1

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4"

dependencies:
  # firebase_auth_platform_interface: ">=4.0.0-1.1.nullsafety.1 <4.0.0-2.0.nullsafety.0"

  firebase_auth_platform_interface: #
    git:
      url: https://github.com/rsixel/flutterfire.git
      path: packages/firebase_auth/firebase_auth_platform_interface

  # firebase_core: ">=0.8.0-1.0.nullsafety.1 <0.8.0-2.0.nullsafety.0"
  firebase_core: 
    git:
      url: https://github.com/rsixel/flutterfire.git
      path: packages/firebase_core/firebase_core

  # firebase_core_web: ">=0.3.0-1.0.nullsafety.1 <0.3.0-2.0.nullsafety.0"
  firebase_core_web: 
    git:
      url: https://github.com/rsixel/flutterfire.git
      path: packages/firebase_core/firebase_core_web
    
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http_parser: ^4.0.0-nullsafety
  intl: ^0.17.0-nullsafety.2
  js: ^0.6.3-nullsafety.3
  meta: ^1.3.0-nullsafety.6

dev_dependencies:
  firebase_auth:
    path: ../firebase_auth
  # firebase_core_platform_interface: ">=4.0.0-1.0.nullsafety.1 <4.0.0-2.0.nullsafety.0"
  firebase_core_platform_interface: 
    git:
      url: https://github.com/rsixel/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseAuthWeb
        fileName: firebase_auth_web.dart
