name: firebase_auth_platform_interface
description: A common platform interface for the firebase_auth plugin.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_auth/firebase_auth_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 4.0.0-1.1.nullsafety.1

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.9.1+hotfix.5"

dependencies:
  # firebase_core: ">=0.8.0-1.0.nullsafety.1 <0.8.0-2.0.nullsafety.0"

  firebase_core: #^0.8.0-1.0.nullsafety.1
    git:
      url: https://github.com/rsixel/flutterfire.git
      path: packages/firebase_core/firebase_core
    
  flutter:
    sdk: flutter
  meta: ^1.3.0-nullsafety.6
  plugin_platform_interface: ^1.1.0-nullsafety.2

dev_dependencies:
  # firebase_core_platform_interface: ">=4.0.0-1.0.nullsafety.1 <4.0.0-2.0.nullsafety.0"
  firebase_core_platform_interface: 
    git:
      url: https://github.com/rsixel/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
  
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0-nullsafety.2
