name: cloud_firestore
description:
  Flutter plugin for Cloud Firestore, a cloud-hosted, noSQL database with
  live synchronization and offline support on Android and iOS.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore
version: 0.17.0-1.0.nullsafety.0

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4"

dependencies:
  # cloud_firestore_platform_interface: ">=4.0.0-1.0.nullsafety.0 <4.0.0-2.0.nullsafety.0"
  # cloud_firestore_web: ">=0.4.0-1.0.nullsafety.0 <0.4.0-2.0.nullsafety.0"
  # firebase_core: ">=0.8.0-1.0.nullsafety.1 <0.8.0-2.0.nullsafety.0"
  # firebase_core_platform_interface: ">=4.0.0-1.0.nullsafety.1 <4.0.0-2.0.nullsafety.0"
  cloud_firestore_platform_interface: 
    git:
      url: https://github.com/rsixel/flutterfire.git
      path: packages/cloud_firestore/cloud_firestore_platform_interface

  cloud_firestore_web: # ^0.17.0-1.0.nullsafety.0
    git:
      url: https://github.com/rsixel/flutterfire.git
      path: packages/cloud_firestore/cloud_firestore_web

  firebase_core: #^0.8.0-1.0.nullsafety.1
    git:
      url: https://github.com/rsixel/flutterfire.git
      path: packages/firebase_core/firebase_core
      
  firebase_core_platform_interface: #^4.0.0-1.0.nullsafety.0
    git:
      url: https://github.com/rsixel/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface


  flutter:
    sdk: flutter

  meta: ^1.3.0-nullsafety.6

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0-nullsafety.2
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.firestore
        pluginClass: FlutterFirebaseFirestorePlugin
      ios:
        pluginClass: FLTFirebaseFirestorePlugin
      macos:
        pluginClass: FLTFirebaseFirestorePlugin
      web:
        default_package: cloud_firestore_web
