name: firebase_auth
description: Flutter plugin for Firebase Auth, enabling Android and iOS
  authentication using passwords, phone numbers and identity providers
  like Google, Facebook and Twitter.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_auth/firebase_auth
version: 0.21.0-1.1.nullsafety.1

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4"

dependencies:
  firebase_auth_platform_interface: ">=4.0.0-1.1.nullsafety.1 <4.0.0-2.0.nullsafety.0"
  firebase_auth_web: ">=0.4.0-1.1.nullsafety.1 <0.4.0-2.0.nullsafety.0"
  # firebase_core: ">=0.8.0-1.0.nullsafety.1 <0.8.0-2.0.nullsafety.0"
  # firebase_core_platform_interface: ">=4.0.0-1.0.nullsafety.1 <4.0.0-2.0.nullsafety.0"


  firebase_core: #^0.8.0-1.0.nullsafety.1
    git:
      url: https://github.com/rsixel/flutterfire.git
      path: packages/firebase_core/firebase_core
      
  firebase_core_platform_interface: #^4.0.0-1.0.nullsafety.0
    git:
      url: https://github.com/rsixel/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
    
  flutter:
    sdk: flutter
  meta: ^1.3.0-nullsafety.6

dev_dependencies:
  async: ^2.5.0-nullsafety.3
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0-nullsafety.2
  plugin_platform_interface: ^1.1.0-nullsafety.2
  test: ^1.16.0-nullsafety.15

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.auth
        pluginClass: FlutterFirebaseAuthPlugin
      ios:
        pluginClass: FLTFirebaseAuthPlugin
      macos:
        pluginClass: FLTFirebaseAuthPlugin
      web:
        default_package: firebase_auth_web
